//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""863af194-71be-4710-941a-c39334081194"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4e065e78-4749-4cd5-a2b2-8dcdc454541e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a0bc722c-2268-4215-9965-9a4a77ec073d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""755bdd1f-1d65-476b-948a-5ac105ca23ec"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""889b0261-c4f0-4a55-b061-c81d0a4f56d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""411930a4-e571-4102-a7e8-85690ddb5de2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDevice"",
                    ""type"": ""Value"",
                    ""id"": ""05509e04-6cff-40c8-ae23-035d3a406139"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeDeviceTo1"",
                    ""type"": ""Button"",
                    ""id"": ""1242d665-bc30-44cf-844b-33122a81d794"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo2"",
                    ""type"": ""Button"",
                    ""id"": ""53c7f08a-2548-4d6e-a994-051e3704ba79"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo3"",
                    ""type"": ""Button"",
                    ""id"": ""c9b498c5-665b-4b41-a9ab-19c80feb3364"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo4"",
                    ""type"": ""Button"",
                    ""id"": ""1d25732f-57a6-460d-ab89-2499fdbe974a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo5"",
                    ""type"": ""Button"",
                    ""id"": ""4372670b-6c92-4ac1-bbe1-f4ff84ec9324"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo6"",
                    ""type"": ""Button"",
                    ""id"": ""f0b278c3-d191-4b75-981e-db096044472c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo7"",
                    ""type"": ""Button"",
                    ""id"": ""e29a7d4a-f6d3-4cf0-97af-91c4b6eb41d6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDeviceTo8"",
                    ""type"": ""Button"",
                    ""id"": ""8ee4c76b-79a8-4dac-be6e-b6c45cd8c483"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2b5cb188-9d07-406c-ad59-abaccf2e7bbb"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""708f7031-5506-4425-9bd5-89b90cc8ec9f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fd8c8706-2edd-42d9-af75-edcea0329aa5"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""31ead649-7a65-405f-bb06-2f19a99db4d9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""757347d1-77b0-4d6a-ad5f-784c729a01fb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1f88cc2b-5a77-45a0-8768-6821d3b2edcd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""86c29f49-9aae-4916-b74e-8f1a6d58912d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c5f9a5cd-40cb-4ad0-b2cb-6ca586c2f068"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f3b2f71d-4c88-424e-a784-5a7746a59e15"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""47e733f2-a4cb-46b0-a775-63443ae4aed9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae04035d-b33d-48f1-9eef-93c42f50bce7"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70a971ef-4136-4094-b069-7fda4f490069"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""268b806f-a9a7-46ba-b387-f71e90e00881"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fac448eb-59b3-4982-82f2-b273456ac74e"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDevice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""350ec0c2-74c7-4671-a7d3-8c3ff2f2e259"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c4b4afa-4fd1-4418-9636-e7126c5764ac"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d165041b-9240-4a73-bcf3-e8d961d0cf0b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""030f6bb9-9158-4a2e-8290-a0030e093286"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdfa5252-8990-40e9-9ea4-b4f9e3324529"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ae4ee5c-d889-40dd-b3cd-cb270d624f6c"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a4d300f-e0e4-4647-bd4f-b1b181141b4a"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d784c29-f208-4fd2-85b4-653aa690a725"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDeviceTo8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""db853a6c-04c4-45fd-b511-b2a8c2859daa"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""a72d76a9-4834-407a-ad7e-1dd8c0eda29f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f3064650-6791-4645-9e57-222aeba8bde4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Device"",
            ""id"": ""42e781a1-2a42-46df-a92a-ad81281ed841"",
            ""actions"": [
                {
                    ""name"": ""LeftMouseInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""bde296c6-bfcd-4b36-a2e0-702b157b232b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""acb2fec3-782c-4af5-8724-5e108553929a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Value"",
                    ""id"": ""df11ff54-2a8e-4443-862d-939d07c82a90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5b9cfb15-7be6-455f-9bfb-4f4860c76b6e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""664ea921-417d-4fe4-9413-c851745c8c7e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c763923f-7eba-4a4c-bd35-36919d95d11d"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_ScrollDevice = m_Player.FindAction("ScrollDevice", throwIfNotFound: true);
        m_Player_ChangeDeviceTo1 = m_Player.FindAction("ChangeDeviceTo1", throwIfNotFound: true);
        m_Player_ChangeDeviceTo2 = m_Player.FindAction("ChangeDeviceTo2", throwIfNotFound: true);
        m_Player_ChangeDeviceTo3 = m_Player.FindAction("ChangeDeviceTo3", throwIfNotFound: true);
        m_Player_ChangeDeviceTo4 = m_Player.FindAction("ChangeDeviceTo4", throwIfNotFound: true);
        m_Player_ChangeDeviceTo5 = m_Player.FindAction("ChangeDeviceTo5", throwIfNotFound: true);
        m_Player_ChangeDeviceTo6 = m_Player.FindAction("ChangeDeviceTo6", throwIfNotFound: true);
        m_Player_ChangeDeviceTo7 = m_Player.FindAction("ChangeDeviceTo7", throwIfNotFound: true);
        m_Player_ChangeDeviceTo8 = m_Player.FindAction("ChangeDeviceTo8", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Newaction = m_UI.FindAction("New action", throwIfNotFound: true);
        // Device
        m_Device = asset.FindActionMap("Device", throwIfNotFound: true);
        m_Device_LeftMouseInteraction = m_Device.FindAction("LeftMouseInteraction", throwIfNotFound: true);
        m_Device_RightMouseInteraction = m_Device.FindAction("RightMouseInteraction", throwIfNotFound: true);
        m_Device_MouseScroll = m_Device.FindAction("MouseScroll", throwIfNotFound: true);
    }

    ~@GameInput()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, GameInput.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, GameInput.UI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Device.enabled, "This will cause a leak and performance issues, GameInput.Device.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_ScrollDevice;
    private readonly InputAction m_Player_ChangeDeviceTo1;
    private readonly InputAction m_Player_ChangeDeviceTo2;
    private readonly InputAction m_Player_ChangeDeviceTo3;
    private readonly InputAction m_Player_ChangeDeviceTo4;
    private readonly InputAction m_Player_ChangeDeviceTo5;
    private readonly InputAction m_Player_ChangeDeviceTo6;
    private readonly InputAction m_Player_ChangeDeviceTo7;
    private readonly InputAction m_Player_ChangeDeviceTo8;
    public struct PlayerActions
    {
        private @GameInput m_Wrapper;
        public PlayerActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @ScrollDevice => m_Wrapper.m_Player_ScrollDevice;
        public InputAction @ChangeDeviceTo1 => m_Wrapper.m_Player_ChangeDeviceTo1;
        public InputAction @ChangeDeviceTo2 => m_Wrapper.m_Player_ChangeDeviceTo2;
        public InputAction @ChangeDeviceTo3 => m_Wrapper.m_Player_ChangeDeviceTo3;
        public InputAction @ChangeDeviceTo4 => m_Wrapper.m_Player_ChangeDeviceTo4;
        public InputAction @ChangeDeviceTo5 => m_Wrapper.m_Player_ChangeDeviceTo5;
        public InputAction @ChangeDeviceTo6 => m_Wrapper.m_Player_ChangeDeviceTo6;
        public InputAction @ChangeDeviceTo7 => m_Wrapper.m_Player_ChangeDeviceTo7;
        public InputAction @ChangeDeviceTo8 => m_Wrapper.m_Player_ChangeDeviceTo8;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @ScrollDevice.started += instance.OnScrollDevice;
            @ScrollDevice.performed += instance.OnScrollDevice;
            @ScrollDevice.canceled += instance.OnScrollDevice;
            @ChangeDeviceTo1.started += instance.OnChangeDeviceTo1;
            @ChangeDeviceTo1.performed += instance.OnChangeDeviceTo1;
            @ChangeDeviceTo1.canceled += instance.OnChangeDeviceTo1;
            @ChangeDeviceTo2.started += instance.OnChangeDeviceTo2;
            @ChangeDeviceTo2.performed += instance.OnChangeDeviceTo2;
            @ChangeDeviceTo2.canceled += instance.OnChangeDeviceTo2;
            @ChangeDeviceTo3.started += instance.OnChangeDeviceTo3;
            @ChangeDeviceTo3.performed += instance.OnChangeDeviceTo3;
            @ChangeDeviceTo3.canceled += instance.OnChangeDeviceTo3;
            @ChangeDeviceTo4.started += instance.OnChangeDeviceTo4;
            @ChangeDeviceTo4.performed += instance.OnChangeDeviceTo4;
            @ChangeDeviceTo4.canceled += instance.OnChangeDeviceTo4;
            @ChangeDeviceTo5.started += instance.OnChangeDeviceTo5;
            @ChangeDeviceTo5.performed += instance.OnChangeDeviceTo5;
            @ChangeDeviceTo5.canceled += instance.OnChangeDeviceTo5;
            @ChangeDeviceTo6.started += instance.OnChangeDeviceTo6;
            @ChangeDeviceTo6.performed += instance.OnChangeDeviceTo6;
            @ChangeDeviceTo6.canceled += instance.OnChangeDeviceTo6;
            @ChangeDeviceTo7.started += instance.OnChangeDeviceTo7;
            @ChangeDeviceTo7.performed += instance.OnChangeDeviceTo7;
            @ChangeDeviceTo7.canceled += instance.OnChangeDeviceTo7;
            @ChangeDeviceTo8.started += instance.OnChangeDeviceTo8;
            @ChangeDeviceTo8.performed += instance.OnChangeDeviceTo8;
            @ChangeDeviceTo8.canceled += instance.OnChangeDeviceTo8;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @ScrollDevice.started -= instance.OnScrollDevice;
            @ScrollDevice.performed -= instance.OnScrollDevice;
            @ScrollDevice.canceled -= instance.OnScrollDevice;
            @ChangeDeviceTo1.started -= instance.OnChangeDeviceTo1;
            @ChangeDeviceTo1.performed -= instance.OnChangeDeviceTo1;
            @ChangeDeviceTo1.canceled -= instance.OnChangeDeviceTo1;
            @ChangeDeviceTo2.started -= instance.OnChangeDeviceTo2;
            @ChangeDeviceTo2.performed -= instance.OnChangeDeviceTo2;
            @ChangeDeviceTo2.canceled -= instance.OnChangeDeviceTo2;
            @ChangeDeviceTo3.started -= instance.OnChangeDeviceTo3;
            @ChangeDeviceTo3.performed -= instance.OnChangeDeviceTo3;
            @ChangeDeviceTo3.canceled -= instance.OnChangeDeviceTo3;
            @ChangeDeviceTo4.started -= instance.OnChangeDeviceTo4;
            @ChangeDeviceTo4.performed -= instance.OnChangeDeviceTo4;
            @ChangeDeviceTo4.canceled -= instance.OnChangeDeviceTo4;
            @ChangeDeviceTo5.started -= instance.OnChangeDeviceTo5;
            @ChangeDeviceTo5.performed -= instance.OnChangeDeviceTo5;
            @ChangeDeviceTo5.canceled -= instance.OnChangeDeviceTo5;
            @ChangeDeviceTo6.started -= instance.OnChangeDeviceTo6;
            @ChangeDeviceTo6.performed -= instance.OnChangeDeviceTo6;
            @ChangeDeviceTo6.canceled -= instance.OnChangeDeviceTo6;
            @ChangeDeviceTo7.started -= instance.OnChangeDeviceTo7;
            @ChangeDeviceTo7.performed -= instance.OnChangeDeviceTo7;
            @ChangeDeviceTo7.canceled -= instance.OnChangeDeviceTo7;
            @ChangeDeviceTo8.started -= instance.OnChangeDeviceTo8;
            @ChangeDeviceTo8.performed -= instance.OnChangeDeviceTo8;
            @ChangeDeviceTo8.canceled -= instance.OnChangeDeviceTo8;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Newaction;
    public struct UIActions
    {
        private @GameInput m_Wrapper;
        public UIActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_UI_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // Device
    private readonly InputActionMap m_Device;
    private List<IDeviceActions> m_DeviceActionsCallbackInterfaces = new List<IDeviceActions>();
    private readonly InputAction m_Device_LeftMouseInteraction;
    private readonly InputAction m_Device_RightMouseInteraction;
    private readonly InputAction m_Device_MouseScroll;
    public struct DeviceActions
    {
        private @GameInput m_Wrapper;
        public DeviceActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftMouseInteraction => m_Wrapper.m_Device_LeftMouseInteraction;
        public InputAction @RightMouseInteraction => m_Wrapper.m_Device_RightMouseInteraction;
        public InputAction @MouseScroll => m_Wrapper.m_Device_MouseScroll;
        public InputActionMap Get() { return m_Wrapper.m_Device; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DeviceActions set) { return set.Get(); }
        public void AddCallbacks(IDeviceActions instance)
        {
            if (instance == null || m_Wrapper.m_DeviceActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DeviceActionsCallbackInterfaces.Add(instance);
            @LeftMouseInteraction.started += instance.OnLeftMouseInteraction;
            @LeftMouseInteraction.performed += instance.OnLeftMouseInteraction;
            @LeftMouseInteraction.canceled += instance.OnLeftMouseInteraction;
            @RightMouseInteraction.started += instance.OnRightMouseInteraction;
            @RightMouseInteraction.performed += instance.OnRightMouseInteraction;
            @RightMouseInteraction.canceled += instance.OnRightMouseInteraction;
            @MouseScroll.started += instance.OnMouseScroll;
            @MouseScroll.performed += instance.OnMouseScroll;
            @MouseScroll.canceled += instance.OnMouseScroll;
        }

        private void UnregisterCallbacks(IDeviceActions instance)
        {
            @LeftMouseInteraction.started -= instance.OnLeftMouseInteraction;
            @LeftMouseInteraction.performed -= instance.OnLeftMouseInteraction;
            @LeftMouseInteraction.canceled -= instance.OnLeftMouseInteraction;
            @RightMouseInteraction.started -= instance.OnRightMouseInteraction;
            @RightMouseInteraction.performed -= instance.OnRightMouseInteraction;
            @RightMouseInteraction.canceled -= instance.OnRightMouseInteraction;
            @MouseScroll.started -= instance.OnMouseScroll;
            @MouseScroll.performed -= instance.OnMouseScroll;
            @MouseScroll.canceled -= instance.OnMouseScroll;
        }

        public void RemoveCallbacks(IDeviceActions instance)
        {
            if (m_Wrapper.m_DeviceActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDeviceActions instance)
        {
            foreach (var item in m_Wrapper.m_DeviceActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DeviceActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DeviceActions @Device => new DeviceActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnScrollDevice(InputAction.CallbackContext context);
        void OnChangeDeviceTo1(InputAction.CallbackContext context);
        void OnChangeDeviceTo2(InputAction.CallbackContext context);
        void OnChangeDeviceTo3(InputAction.CallbackContext context);
        void OnChangeDeviceTo4(InputAction.CallbackContext context);
        void OnChangeDeviceTo5(InputAction.CallbackContext context);
        void OnChangeDeviceTo6(InputAction.CallbackContext context);
        void OnChangeDeviceTo7(InputAction.CallbackContext context);
        void OnChangeDeviceTo8(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IDeviceActions
    {
        void OnLeftMouseInteraction(InputAction.CallbackContext context);
        void OnRightMouseInteraction(InputAction.CallbackContext context);
        void OnMouseScroll(InputAction.CallbackContext context);
    }
}
